<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-O89G6D4" failures="1" tests="10" name="advanced.TestNGAnnotations" time="0.216" errors="0" timestamp="2023-07-19T09:14:23 IST" skipped="0">
  <testcase classname="advanced.TestNGAnnotations" name="getTestData" time="0.009"/>
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="getTestData" time="0.012"/>
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="getTestData" time="0.023"/>
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="verifyHeaderText" time="0.019"/>
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="getTestData" time="0.016"/>
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="getTestData" time="0.007"/>
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="checkout" time="0.010"/>
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="OTPValidation" time="0.011"/>
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="login" time="0.099">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at advanced.TestNGAnnotations.login(TestNGAnnotations.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
  <testcase classname="advanced.TestNGAnnotations" name="addtoCart" time="0.010"/>
  <system-out/>
</testsuite> <!-- advanced.TestNGAnnotations -->
